name: hi_core
description: core of hi_flutter.
version: 1.1.1
publish_to: 'none'
repository: https://github.com/tospery/flutter/tree/main/packages/hi_core
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_core%22

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hi_base: 
    path: ../hi_base
  hi_logger:
    path: ../hi_logger
  hi_resource:
    path: ../hi_resource

dev_dependencies:
  flutter_test:
    sdk: flutter

