name: hi_core
description: core of hi_flutter.
version: 1.0.2
repository: https://github.com/tospery/flutter/tree/main/packages/hi_core
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_core%22

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hi_base: ^1.1.0
  hi_res: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

