name: hi_base
description: This library is a basic utility library that includes conversions between fundamental data types and definitions of basic model type.
version: 1.1.0
repository: https://github.com/tospery/flutter/tree/main/packages/hi_base
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_base%22

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter