name: hi_flutter
description: flutter app framework.
version: 0.0.1
repository: https://github.com/tospery/flutter/tree/main/packages/hi_flutter
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_flutter%22

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.5
  event_bus: 2.0.0
  package_info_plus: 1.4.3+1
  cached_network_image: 3.2.1
  pull_to_refresh: 2.0.0
  flutter_svg: 1.1.5
  lottie: 1.4.2
  webview_flutter: 3.0.4
  hi_core:
    path: ../hi_core
  hi_navigator:
    path: ../hi_navigator
  hi_cache:
    path: ../hi_cache
  hi_network:
    path: ../hi_network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
