name: hi_flutter
description: Flutter App Framework
version: 1.0.0
homepage: https://github.com/tospery/flutter/packages/hi_flutter

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # core
  logger: 1.1.0
  equatable: 2.0.5
  # cache
  shared_preferences: 2.0.15
  sqflite: 2.0.3+1
  cv: 0.2.8+1
  # frame
  get: 4.6.5
  flukit: 3.0.1
  getwidget: 3.0.1
  webview_flutter: 3.0.4
  pull_to_refresh: 2.0.0
  cached_network_image: 3.2.1
  flutter_svg: 1.1.5
  lottie: 1.4.2
  flutter_spinkit: 5.1.0
  flutter_easyloading: 3.0.5
  adaptive_dialog: 1.8.0
  fluttertoast: 8.0.9
  package_info_plus: 1.4.3+1
  event_bus: 2.0.0

  # hi_core:
  #   path: ../hi_core
  # hi_cache:
  #   path: ../hi_cache
  # hi_frame:
  #   path: ../hi_frame

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

