name: hi_flutter
description: flutter app framework.
version: 1.1.0
publish_to: 'none'
repository: https://github.com/tospery/flutter/tree/main/packages/hi_flutter
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_flutter%22

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  event_bus: ^2.0.1
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.2.1
  lottie: ^3.3.1
  webview_flutter: ^4.13.0
  linkify: ^5.0.0
  # flutter_linkify: 5.0.2
  hi_base:
    path: ../hi_base
  hi_core:
    path: ../hi_core
  hi_navigator:
    path: ../hi_navigator
  hi_cache:
    path: ../hi_cache
  hi_network:
    path: ../hi_network

dev_dependencies:
  flutter_test:
    sdk: flutter
