name: hi_flutter
description: flutter app framework.
version: 0.0.1
repository: https://github.com/tospery/flutter/tree/main/packages/hi_flutter
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_flutter%22

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  event_bus: 2.0.0
  package_info_plus: 6.0.0
  device_info_plus: 10.0.1
  cached_network_image: 3.3.1
  pull_to_refresh: 2.0.0
  flutter_svg: 2.0.10+1
  lottie: 3.1.0
  webview_flutter: 4.7.0
  linkify: 5.0.0
  # flutter_linkify: 5.0.2
  hi_core:
    path: ../hi_core
  hi_navigator:
    path: ../hi_navigator
  hi_cache:
    path: ../hi_cache
  hi_network:
    path: ../hi_network

dev_dependencies:
  flutter_test:
    sdk: flutter
