name: hi_network
description: network of hi_flutter.
version: 1.1.0
publish_to: 'none'
repository: https://github.com/tospery/flutter/tree/main/packages/hi_network
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_network%22

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  hi_core:
    path: ../hi_core

dev_dependencies:
  flutter_test:
    sdk: flutter