name: hi_logger
description: An abstraction layer for a basic logging library, implemented using the third-party library logger.
version: 1.0.0
repository: https://github.com/tospery/flutter/tree/main/packages/hi_logger
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_logger%22

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter