name: hi_log
description: log of hi_flutter.
version: 1.0.0
repository: https://github.com/tospery/flutter/tree/main/packages/hi_log
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_log%22

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter