name: hi_navigator
description: navigator of hi_flutter.
version: 1.1.0
publish_to: 'none'
repository: https://github.com/tospery/flutter/tree/main/packages/hi_navigator
issue_tracker: https://github.com/tospery/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+hi_navigator%22

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  getwidget: ^6.0.0
  # flutter_spinkit: 5.2.1
  flutter_easyloading: ^3.0.5
  adaptive_dialog: ^2.4.2
  adaptive_action_sheet: ^2.0.4
  fluttertoast: ^8.2.12
  lottie: ^3.3.1
  url_launcher: ^6.3.2
  hi_core:
    path: ../hi_core

dev_dependencies:
  flutter_test:
    sdk: flutter